apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
type: Opaque
data:
  mysql-root-password: {{ required "A valid MySQL root password is required" .Values.mysql.auth.rootPassword | b64enc }}
  mysql-password: {{ required "A valid MySQL password is required" .Values.mysql.auth.password | b64enc }} 